enableAllRules = true

[rule.argument-limit]
    Arguments = [5]
[rule.cyclomatic]
    Arguments = [10]
[rule.cognitive-complexity]
    Arguments = [7]
[rule.function-result-limit]
    Arguments = [3]
[rule.function-length]
    Arguments = [20, 20]
[rule.max-public-structs]
    Arguments = [3]
[rule.line-length-limit]
    Arguments = [128]

[rule.banned-characters]
    Disabled = true
[rule.error-strings]
    Disabled = true
[rule.file-header]
    Disabled = true